CREATE TABLESPACE ts_academico
 DATAFILE 'C:\oracle\oradata\ts_academico01.dbf' SIZE 200M AUTOEXTEND ON NEXT 50M
 EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
 
CREATE TABLESPACE ts_academico_idx
 DATAFILE 'C:\oracle\oradata\ts_academico_idx01.dbf' SIZE 100M AUTOEXTEND ON NEXT 25M
 EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE USER PBASES IDENTIFIED BY 1234
 DEFAULT TABLESPACE ts_academico
 TEMPORARY TABLESPACE temp
 QUOTA UNLIMITED ON ts_academico;
 
GRANT CONNECT, RESOURCE TO PBASES;

ALTER USER PBASES QUOTA UNLIMITED ON ts_academico;
ALTER USER PBASES QUOTA UNLIMITED ON ts_academico_idx;
